version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      -  ./app/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./app/html:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
