name: heroku

on: [ push ]

env:
  DOCKER_BUILDKIT: 1
  IMAGE_NAME: sample_app
  IMAGE_TAG: test
  APP_NAME:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: ls -a
      - name: Node, npm setup
        uses: actions/setup-node@v1
      - run: npm install


  heroku-access:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Heroku setup
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          heroku -v








