name: heroku

on: [ push ]

env:
  DOCKER_BUILDKIT: 1
  APP_NAME: heroku-sample-deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Heroku setup
        run: curl https://cli-assets.heroku.com/install.sh | sh
      - name: Heroku login
        run: |
          `cat >~/.netrc <<EOF
          machine api.heroku.com
              login ${{ secrets.HEROKU_USER }}
              password ${{ secrets.HEROKU_APIKEY }}
          machine git.heroku.com
              login ${{ secrets.HEROKU_USER }}
              password ${{ secrets.HEROKU_APIKEY }}
          EOF`
          heroku container:login
      - name: Heroku push
        run: heroku container:push web -a ${APP_NAME}
      - name: Heroku release
        run: heroku container:release web -a ${APP_NAME}








