name: heroku

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: docker build -t heroku-sample:1.0 .


  heroku-access:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl https://cli-assets.heroku.com/install.sh | sh
      - run: heroku -v



